### ISSUE TITLE
Inquiring about compiling

### ISSUE THREAD

**Issue by El-No** [brodeau/aerobulk#5]
Dear Aerobulk Project Manager.

First of all, thank you very much for sharing useful code.
I have a few questions while compiling.

First, When I set make.macro only with **FF=ifort** and run it, aerobulk_toy.x is successfully executed, but example_call_aerobulk.x is not executed.

Is the problem of example_call_aerobulk.x not executing is the problem of make.macro?
Any comments on the configuration of make.macro would be appreciated.

Second, How do I use a 3D variable with a time axis as input data?
If you don’t mind me asking, please explain in detail the coding compiling.

I look forward to hearing from you.
Sincerely yours.

**Comment by brodeau** [comment]
Hi,

First, two template compiler-specific "make.macro" are provided in the `arch` sub-directory. In your case, since you are using ifort (like me), you might get some inspiration from the ``arch/make.macro_ifort``. I just tested it, it works for me!

Second, *AeroBulk* is meant to handle 2D horizontal spatial arrays... So introduce a `DO loop` along time in your program and call the routines like this:

      DO jt = 1, Nt
         ...
        CALL routine(..., X(:,:,jt), Y(:,:,jt), ...)
        ... 
      END DO

Hope this helps,
/laurent
